### ISSUE TITLE
Reducing default set of packages

### ISSUE THREAD

**Issue by asmeurer** [sympy/live#11]
I noticed that matplotlib and numpy are always loaded by default, if I understand the console output correctly.

Can we make it so that they are not loaded by default? It seems that most packages work like this, where if you import something like `scipy` it loads it. That would presumably make the initial loading time faster.

**Comment by jtpio** [comment]
I think this is likely fixed in the latest versions of the `jupyterlite-core` and `jupyterlite-pyodide-kernel` packages.

The relevant PR being https://github.com/jupyterlite/jupyterlite/pull/911.

**Comment by jtpio** [comment]
> unless they are imported explicitly by the user #18. Do the recent changes affect that?

This is likely still the case with the latest versions. iirc Pyodide detects `import` statements and loads the appropriate packages accordingly.

Not sure we can have both. As an alternative we could also try using the xeus python kernel to only include a subset of packages and not rely on the default versions provided by Pyodide: https://github.com/jupyterlite/xeus-python-kernel. But with that kernel the packages will be loaded at startup as well and not lazily (at least not for now).

**Comment by asmeurer** [comment]
But why doesn't it operate on import statements from within sympy? Internally `sympy.plot` calls `import matplotlib` to see if it's installed, but that doesn't trigger installation. Only `import matplotlib` in the jupyterlite REPL itself does.

**Comment by jtpio** [comment]
If I remember correctly Pyodide parses the source submitted by a user and look for `import` statements. But I don't think it does this for imports within a module.
