### ISSUE TITLE
Example expression that works in Firefox but not in Chrome

### ISSUE THREAD

**Issue by ivanistheone** [sympy/live#17]
When trying to open the live shell today https://live.sympy.org/ in Chrome ( Version 110.0.5481.100  on macOS) , it hands after a few lines and I get this error in the console:

<img width="690" alt="error" src="https://user-images.githubusercontent.com/163966/220169180-66da0a45-1d8e-46c7-999f-230ebcd2dc1e.png">

```
Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (pyodide.asm.js:10:175980)
    at _abort (pyodide.asm.js:10:411862)
    at pyodide.asm.wasm:0x22c022
    at pyodide.asm.wasm:0x22a400
    at pyodide.asm.wasm:0x22bdc0
    at pyodide.asm.wasm:0x1e408d
    at pyodide.asm.wasm:0x2307ea
    at pyodide.asm.wasm:0x17c81a
    at pyodide.asm.wasm:0x1721c1
    at pyodide.asm.wasm:0x14a6f0

broadcast.ts:62 Uncaught (in promise) TypeError: Cannot destructure property 'path' of 'a' as it is null.
    at BroadcastChannel._onMessage (broadcast.ts:62:13)
```

The error doesn't seem to be consistent (it worked a few times).

The live shell works fine in Firefox.

@jtpio  Do you know what this might be?

**Comment by ivanistheone** [comment]
Here is the specific [session link](https://live.sympy.org/?evaluate=alpha%2C%20beta%2C%20mean%2C%20var%20%3D%20symbols(%27%5C%5Calpha%20%5C%5Cbeta%20%5C%5Cmu%20%5C%5Csigma%5E2%27)%0A%23--%0A%23%20define%20two%20expressions%20equal%20to%20zero%0Aexpr1%20%3D%20mean%20-%20alpha%20%2F%20(alpha%2Bbeta)%0Aexpr2%20%3D%20var%20-%20alpha*beta%20%2F(%20(alpha%2Bbeta)**2%20*%20(alpha%2Bbeta%2B1)%20)%0A%23--%0A%23%20%20%20%20%20solve%20system%20of%20two%20equations%0A%23%20%20%20%20%20%20%20%20%20%20%20%20expr1%20%3D%200%0A%23%20%20%20%20%20%20%20%20%20%20%20%20expr2%20%3D%200%0A%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20for%20alpha%2Cbeta%0Asol%20%3D%20solve(%5Bexpr1%2C%20expr2%5D%2C%20%5Balpha%2Cbeta%5D)%5B0%5D%0Asol%0A%23--%0A%23%20split%20two%20parts%20of%20the%20solution%0Asol_alpha%2C%20sol_beta%20%3D%20sol%0A%23--%0A%23%20alpha%20in%20terms%20of%20mean%20and%20var%0Asol_alpha%20%0A%23--%0A%23%20beta%20in%20terms%20of%20mean%20and%20var%0Asol_beta%0A%23--%0A%23%20beta%20in%20terms%20of%20mean%2C%20var%2C%20and%20alpha%0Asimplify(sol_beta%2Fsol_alpha)*alpha%0A) that I am using right now, where it seems to crash halfway through the execution of the commands:

<img width="719" alt="Screen Shot 2023-02-20 at 12 29 38 PM" src="https://user-images.githubusercontent.com/163966/220170086-ef61f794-ce09-4f2b-ae88-c5199030c2d5.png">

Note it rand the first 6 commands successfully, but fails on 7th.

**Comment by ivanistheone** [comment]
Update: the issue only occurs if I open the link in a **new background tab and I don't switch to it**.

To reproduce:
- right click the [saved session link](https://live.sympy.org/?evaluate=alpha%2C%20beta%2C%20mean%2C%20var%20%3D%20symbols(%27%5C%5Calpha%20%5C%5Cbeta%20%5C%5Cmu%20%5C%5Csigma%5E2%27)%0A%23--%0A%23%20define%20two%20expressions%20equal%20to%20zero%0Aexpr1%20%3D%20mean%20-%20alpha%20%2F%20(alpha%2Bbeta)%0Aexpr2%20%3D%20var%20-%20alpha*beta%20%2F(%20(alpha%2Bbeta)**2%20*%20(alpha%2Bbeta%2B1)%20)%0A%23--%0A%23%20%20%20%20%20solve%20system%20of%20two%20equations%0A%23%20%20%20%20%20%20%20%20%20%20%20%20expr1%20%3D%200%0A%23%20%20%20%20%20%20%20%20%20%20%20%20expr2%20%3D%200%0A%23%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20for%20alpha%2Cbeta%0Asol%20%3D%20solve(%5Bexpr1%2C%20expr2%5D%2C%20%5Balpha%2Cbeta%5D)%5B0%5D%0Asol%0A%23--%0A%23%20split%20two%20parts%20of%20the%20solution%0Asol_alpha%2C%20sol_beta%20%3D%20sol%0A%23--%0A%23%20alpha%20in%20terms%20of%20mean%20and%20var%0Asol_alpha%20%0A%23--%0A%23%20beta%20in%20terms%20of%20mean%20and%20var%0Asol_beta%0A%23--%0A%23%20beta%20in%20terms%20of%20mean%2C%20var%2C%20and%20alpha%0Asimplify(sol_beta%2Fsol_alpha)*alpha%0A) and choose open in new tab, but do not switch the browser focus on the new tab.
- wait 10 seconds
- go see the execution in the new tab

**Comment by jtpio** [comment]
Thanks @ivanistheone for all the details.

I'm wondering whether this could be an issue with Pyodide directly.

Would you be able to check with the Pyodide console which is available here? https://pyodide.org/en/stable/console.html

**Comment by ivanistheone** [comment]
I can't reproduce anymore. Seems like it was a transient issue. Closing for now, but I will remember to try stress-testing this kind of long sessions running in the background in the future.

**Comment by jtpio** [comment]
ok thanks @ivanistheone for the update.
